# KontrolDom Framework - Automations
# Przyk≈Çadowe automatyzy

- id: welcome_home
  alias: "Witaj w domu"
  trigger:
    - platform: state
      entity_id: person.person_name
      to: "home"
  action:
    - service: notify.mobile_app
      data:
        message: "Witaj w domu!"
  mode: single
