# KontrolDom Framework - Home Assistant Configuration
homeassistant:
  name: KontrolDom
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Warsaw
  country: PL
  language: pl

default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  dashboards: !include lovelace_dashboards.yaml

automation: !include automations.yaml
script: !include scripts.yaml

# HACS repositories
hacs:
  repositories:
    - url: https://github.com/thomasloven/hass-browser_mod
    - url: https://github.com/thomasloven/lovelace-card-mod
